   <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
        <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray">Mis Talleres</h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
      
      <form class="was-validated" accept-charset="utf-8" id="formulario">
        <div class="row g-3">

              <!-- ============= TABLA ============= -->
              <div class="col-md-12 my-2">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="col">#</th>
                        <th class="col">Taller</th>
                        <th class="col">F. Inscripción</th>
                        <th class="col">Situación De Cursada</th>
                        <th class="col">Diploma</th>
                        <th class="col"><div class="d-grid ps-md-2 pe-md-4"><button type="button" class="btn btn-sm btn-outline-primary" id="btn_agregar_inscripcion">Agregar</button></div></th>
                      </tr>
                    </thead>
                    <tbody id="contenidoTablaInscripcion"></tbody>
                  </table>
                </div>
              </div>

        </div>
      </form>

    </main>

    <script type="text/javascript">

        var inscripcion_id_seleccionado;
        var usuario_id_seleccionado;
        var taller_id_seleccionado;

        $("#btn_agregar_inscripcion").click( () => {
          let id_tmp = Math.floor(Math.random() * 999999999999999);
          inscripcion_id_seleccionado = id_tmp;
          $('#contenidoTablaInscripcion').append( 
              '<tr id="' + id_tmp + '">' +
                  '<th scope="row"><p class="text-center pt-1" id="inscripcion_id' + id_tmp + '">N</th>' +
                  '<td>' + 
                      '<select class="form-select form-select-sm" id="inscripcion_taller' + id_tmp + '" style="width: 350px;">' +
                        $.ajax({
                          method: 'GET',
                          dataType: 'JSON',
                          url: '/controlador/c_taller.php/?operacion=listar&filtro=taller_disponibilidad&valor=',
                        }).done( (res) => {
                          if(typeof(res[0]) != "undefined") {
                            for (let i = 0; i < res.length; i++) {
                              $('#inscripcion_taller' + id_tmp).append( 
                                '<option  ' + ((i == 0) ? "selected":"") + ' value="' + res[i].id + '">' + res[i].titulo + ' (Días & Horarios: ' + res[i].dia_horario + ' - Cupo: ' + res[i].cupo_actual + ')</option>');
                            }             
                          }
                        }) + 
                      '</select>' +
                  '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_fecha_inscripcion' + id_tmp + '" style="width: 100px;">' + fechaActual() + '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_situacion_cursada' + id_tmp + '" style="width: 100px;">PENDIENTE</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_diploma' + id_tmp + '">NO</td>' +
                  '<td class="btn-group">' +
                      '<button type="button" class="btn btn-sm btn-dark" id="btnGuardar' + id_tmp + '" onclick="guardarInscripcion(\'insertar\', ' + id_tmp + ');">Guardar</button>' +
                      '<button type="button" class="btn btn-sm btn-danger" id="btnQuitar' + id_tmp + '" onclick="quitarInscripcionTMP(' + id_tmp + ');">Quitar</button>' +
                  '</td>' +
              '</tr>');
        });

        function guardarInscripcion(operacion, id){
          if (confirmarMSJ('guardar el nuevo registro') === true){
            $.ajax({
                method: "POST",
                dataType: 'JSON',
                url: '/controlador/c_inscripcion.php/?operacion=' + operacion,
                data: { 
                    'id' : inscripcion_id_seleccionado,
                    'usuario_id' : usuario_id_seleccionado,
                    'taller_id' : $("#inscripcion_taller" + id).val(),
                    "fecha_inscripcion" : $("#inscripcion_fecha_inscripcion" + id).html(),
                    "asistencia_final" : 0,
                    "calificacion_final" : 0,
                    "situacion_cursada" : $("#inscripcion_situacion_cursada" + id).html() }
            }).done( (res) => { 
                if (res.estado) {
                  $('#' + id).attr("id", res.id);
                  $('#inscripcion_id' + id).attr("id", "inscripcion_id" + res.id).text(res.id);
                  $('#inscripcion_taller' + id).attr("id", "inscripcion_taller" + res.id).prop('disabled', true);
                  $('#inscripcion_fecha_inscripcion' + id).attr("id", "inscripcion_fecha_inscripcion" + res.id);
                  $('#inscripcion_situacion_cursada' + id).attr("id", "inscripcion_situacion_cursada" + res.id);
                  $('#inscripcion_diploma' + id).attr("id", "inscripcion_diploma" + res.id);
                  $('#btnGuardar' + id).remove();
                  $('#btnQuitar' + id).remove();                  
                }
                mensajeDeRespuesta = res.mensaje;
            }).then( ()=> {
                alert(mensajeDeRespuesta);
            });
          }
        }

        function listarInscripcion(filtro, valor) {
          $('#contenidoTablaInscripcion').empty();
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_inscripcion.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => {
            for (let i = 0; i < res.length; i++) {
              $('#contenidoTablaInscripcion').append( 
                '<tr id="' + res[i].id + '">' +
                  '<th scope="row"><p class="text-center pt-1" id="inscripcion_id' + res[i].id + '">' + res[i].id + '</th>' +
                  '<td>' +
                    '<p class="text-center pt-1" id="inscripcion_taller' + res[i].id + '" style="width: 350px;">' + 
                        $.ajax({
                          method: 'GET',
                          dataType: 'JSON',
                          url: '/controlador/c_taller.php/?operacion=obtener&id=' + res[i].taller_id,
                        }).done( (resTaller) => {
                          if(typeof(resTaller) != "undefined") {
                              $('#inscripcion_taller' + res[i].id).html( 
                                resTaller.titulo + ' (Descripción: ' + resTaller.dia_horario + ' - Cupo: ' + resTaller.cupo_actual + ')');
                          }
                        }) + 
                    '</p>' +
                  '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_fecha_inscripcion' + res[i].id + '" style="width: 100px;">' + res[i].fecha_inscripcion + '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_situacion_cursada' + res[i].id + '" style="width: 100px;">' + res[i].situacion_cursada + '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_diploma' + res[i].id + '">' + ((res[i].diploma.id == null) ? 'NO':'SI') + '</td>' +
                  '<td class="btn-group">' +
                      '<button type="button" class="btn btn-sm btn-dark" id="btnVer' + res[i].id + '" onclick="verDiploma(' + res[i].id + ');" ' + ((res[i].diploma.id == null) ? ' disabled hidden':'') + '>Ver Diploma</button>' +
                  '</td>' +
              '</tr>');
            }
          });               
        }

        function quitarInscripcionTMP(id){
          $('#' + id).remove();                   
        }

        function verDiploma(inscripcion_id){
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_diploma.php/?operacion=confeccionar&inscripcion_id=' + inscripcion_id
          }).done( async (res) => {
            await jQuery('<form target="_blank" action="' + res.ruta + '" method="get"></form>').appendTo('body').submit().remove();
          });
        }

        function confirmarMSJ(mensaje){
          return confirm('¿Está seguro que quiere ' + mensaje);
        }

        //Acción: Auto-carga las inscripciones correspondientes al usuario que accedio al sistema 
        $.ajax({
          method: 'GET',
          dataType: 'JSON',
          url: '/controlador/c_usuario.php/?operacion=obtenerSesion'
        }).done( async (res) => {
          usuario_id_seleccionado = await res.id;
          await listarInscripcion('usuario_id', usuario_id_seleccionado);
        });
        
    </script>