    <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
        <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray">Plantilla</h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
        <form>
        </form>
    </main>

    <script type="text/javascript">
            

    </script>