   <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
        <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray">Gestión De Inscripciones </h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
      <form class="was-validated" accept-charset="utf-8" id="formulario">
        <h5 class="text-center my-2" id="subtitulo_titulo"></h5>
        <div class="row justify-content-center">
          <h6 class="col-sm-6 text-center text-secondary" id="contenedor_fecha1"></h6>
          <div class="row justify-content-center">
            <h6 class="col-auto text-secondary" id="subtitulo_fecha_inicio"></h6><h6 class="col-auto text-secondary" id="contenedor_fecha2"></h6><h6 class="col-auto text-secondary" id="subtitulo_fecha_cierre"></h6>
          </div>
          <div class="row justify-content-center mb-3">
          <h6 class="col-auto text-right text-secondary" id="contenedor_carga_horaria"></h6><h6 class="col-auto text-secondary" id="subtitulo_carga_horaria"></h6>
          </div>          
        </div>
        <div class="row g-3">

          <!-- ============= TABLA ============= -->
          <div class="col-md-12 my-2">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th class="col">#</th>
                    <th class="col">Taller</th>
                    <th class="col">F. Inscripción</th>
                    <th class="col">Asist. Final</th>
                    <th class="col">Calif. Final</th>
                    <th class="col">Situación De Cursada</th>
                    <th class="col">Diploma</th>
                    <th class="col">BlockChain N°</th>
                    <th class="col"></th>
                  </tr>
                </thead>
                <tbody id="contenidoTablaInscripcion"></tbody>
              </table>
            </div>
          </div>

          <!-- ============ BOTONES ============ -->
          <div class="col-md-12">
            <div class="row mt-3">
              <div class="col-md-4 offset-md-4 col-lg-2 offset-lg-5 my-1"><div class="d-grid gap-2"><button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#listadoModal" id="btn_buscar_taller">Buscar Taller</button></div></div>
            </div>
          </div>

        </div>
      </form>
    </main>

    <!-- =================== PANEL: IMAGEN LOADING =================== -->
    <div class="text-center my-3" id="loading" hidden>
      <img src="img/ajax-loader.gif"><br/>
      Registrando el diploma en la Blockchain.<br>
      El proceso puede tardar varios segundos…
    </div>

    <!-- ==================== PANEL: LISTADO MODAL =================== -->
    <div class="modal fade" id="listadoModal" tabindex="-1" aria-labelledby="listadoModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="listadoModalLabel">Listado De Talleres</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <!-- ========= BOTONES MODAL ========= -->
            <div class="row">
              <div class="col-md-4  my-1"><div class="d-grid gap-2"><input type="text" class="form-control form-control-sm" id="valor_lista_modal"></div></div>
              <div class="col-md-5  my-1"><div class="d-grid gap-2">
                <select class="form-select form-select-sm" id="filtro_tabla-modal">
                  <option value="id">ID Taller</option>
                  <option selected value="titulo">Título</option>
                </select>
              </div></div>
              <div class="col-md-3  my-1"><div class="d-grid gap-2"><button type="button" class="btn btn-sm btn-primary" id="btn_filtrar_tabla_modal">Buscar</button></div></div>
            </div>
            <!-- ========== TABLA MODAL =========== -->
            <div class="col-md-12 my-2">
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th class="col">#</th>
                      <th class="col">Título</th>
                      <th class="col">F. Inicio</th>
                      <th class="col">Cupo Actual</th>
                      <th class="col"></th>
                    </tr>
                  </thead>
                  <tbody id="contenidoTablaModal"></tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <div class="col-12">
              <div class="col-4 offset-4 my-1"><div class="d-grid gap-2"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button></div></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">

        var mensajeDeRespuesta;     
        var taller_id_seleccionado;
        var diploma_id_generado;
        var nroBloqueBlockChain;

        $("#btn_buscar_taller").click( () => {
          $('#contenidoTablaModal').empty();
        });

        function obtenerTaller(id){
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_taller.php/?operacion=obtener&id=' + id
          }).done( async (res) => { 
            taller_id_seleccionado = res.id;
            await $("#subtitulo_titulo").html(res.titulo);
            await $("#contenedor_fecha1").html('Fecha De Inicio / Cierre:');
            await $("#subtitulo_fecha_inicio").html(res.fecha_inicio);
            await $("#contenedor_fecha2").html('/');
            await $("#subtitulo_fecha_cierre").html(res.fecha_cierre);
            await $("#contenedor_carga_horaria").html('Carga Horaria:');
            await $("#subtitulo_carga_horaria").html(res.carga_horaria + 'hs.');
            subtitulo_carga_horaria
            await listarInscripcion('taller_id', res.id);
          });
        }
        
        function guardarInscripcion(operacion, id){
          if (confirmarMSJ('guardar los cambios realizados?') === true){
            $.ajax({
                method: "POST",
                dataType: 'JSON',
                url: '/controlador/c_inscripcion.php/?operacion=' + operacion,
                data: { 
                    'id' : id,
                    'usuario_id' : $("#inscripcion_usuario_id" + id).html(),
                    'taller_id' : taller_id_seleccionado,
                    "fecha_inscripcion" : $("#inscripcion_fecha_inscripcion" + id).html(),
                    "asistencia_final" : $("#inscripcion_asistencia_final" + id).val(),
                    "calificacion_final" :$("#inscripcion_calificacion_final" + id).val(),
                    "situacion_cursada" : $("#inscripcion_situacion_cursada" + id).val() }
            }).done( (res) => { 
                mensajeDeRespuesta = res.mensaje;
            }).then( ()=> {
                alert(mensajeDeRespuesta);
            });
          }
        }
        
        function listarInscripcion(filtro, valor) {
          $('#contenidoTablaInscripcion').empty();
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_inscripcion.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => {
            for (let i = 0; i < res.length; i++) {
              $('#contenidoTablaInscripcion').append(
                '<tr id="' + res[i].id + '">' +
                  '<th scope="row"><p class="text-center pt-1" id="inscripcion_usuario_id' + res[i].id + '">' + res[i].usuario_id + '</th>' +
                  '<td>' +
                    '<p class="text-center pt-1" id="inscripcion_usuario_apellido_nombre' + res[i].id + '" style="width: 350px;"></p>' + 
                    '<p class="text-center pt-1" id="inscripcion_usuario_documento' + res[i].id + '" hidden></p>' + 
                  '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_fecha_inscripcion' + res[i].id + '" style="width: 100px;">' + res[i].fecha_inscripcion + '</td>' +
                  '<td><input type="number" class="form-control form-control-sm" id="inscripcion_asistencia_final' + res[i].id + '" value="' + res[i].asistencia_final + '" max="99.99" maxlength="5" required style="width: 80px;"></td>' +
                  '<td><input type="number" class="form-control form-control-sm" id="inscripcion_calificacion_final' + res[i].id + '" value="' + res[i].calificacion_final + '" max="99.99" maxlength="5" required style="width: 80px;"></td>' +
                  '<td>' + 
                    '<select class="form-select form-select-sm" id="inscripcion_situacion_cursada' + res[i].id + '" style="width: 170px;">' +
                      '<option ' + ((res[i].situacion_cursada ==='APROBADO') ? "selected":"") + ' value="APROBADO">APROBADO</option>' +
                      '<option ' + ((res[i].situacion_cursada ==='DESAPROBADO') ? "selected":"") + ' value="DESAPROBADO">DESAPROBADO</option>' +
                      '<option ' + ((res[i].situacion_cursada ==='EN CURSO') ? "selected":"") + ' value="EN CURSO">EN CURSO</option>' +
                      '<option ' + ((res[i].situacion_cursada ==='PENDIENTE') ? "selected":"") + ' value="PENDIENTE">PENDIENTE</option>' +
                    '</select>' +
                  '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_diploma' + res[i].id + '">' + ((res[i].diploma.id == null) ? 'NO':'SI') + '</td>' +
                  '<td><p class="text-center pt-1" id="inscripcion_blockchain' + res[i].id + '">' + ((res[i].diploma.bloque_smart_contract == null) ? '': res[i].diploma.bloque_smart_contract) + '</td>' +
                  '<td class="btn-group">' +
                    '<button type="button" class="btn btn-sm btn-dark" id="btnGuardar' + res[i].id + '" onclick="guardarInscripcion(\'actualizar\', ' + res[i].id + ');">Guardar</button>' +
                    '<button type="button" class="btn btn-sm btn-primary" id="btnEmitirDiploma' + res[i].id + '" onclick="emitirDiploma(' + res[i].id +');"' + ((res[i].diploma.id == null) ? '':'disabled hidden') + ' style="width: 110px;">Emitir Diploma</button>' +
                    '<button type="button" class="btn btn-sm btn-success" id="btnVerDiploma' + res[i].id + '" onclick="verDiploma(' + res[i].id +');"' + ((res[i].diploma.id == null) ? 'disabled hidden':'') + ' style="width: 110px;">Ver Diploma</button>' +
                  '</td>' +
                '</tr>' + 
                $.ajax({
                  method: 'GET',
                  dataType: 'JSON',
                  url: '/controlador/c_usuario.php/?operacion=obtener&id=' + res[i].usuario_id,
                }).done( (resUs) => {
                  if(typeof(resUs) != "undefined") {
                      $('#inscripcion_usuario_apellido_nombre' + res[i].id).html( resUs.apellido + ', ' + resUs.nombre);
                      $('#inscripcion_usuario_documento' + res[i].id).html( resUs.documento_tipo.denominacion_corta + ' ' + resUs.documento_nro);
                  }
                }) 
              );
            }
          });               
        }

        async function emitirDiploma(id){
          if (confirmarMSJ('emitir el diploma del usuario ' + $("#inscripcion_usuario_apellido_nombre" + id).html() + '? (El diploma se registra en la Blockchain y No podrá ser modificado después de haberlo emitido)') === true){
            $('#loading').attr("hidden", false); //Muestra la leyenda de loading
            let apellidoNombre = $('#inscripcion_usuario_apellido_nombre' + id).html(),
            documentoTipoNro = $('#inscripcion_usuario_documento' + id).html(),
            tallerTitulo = $('#subtitulo_titulo').html(),
            tallerCargaHoraria = $('#subtitulo_titulo').html(),
            tallerFecha = $('#subtitulo_fecha_cierre').html();
            // ***************** GENERACION DE BLOCKCHAIN ***************** //
            await registrarBlockChain(apellidoNombre, documentoTipoNro, tallerTitulo, tallerCargaHoraria, tallerFecha).then( function(res){ 
              nroBloqueBlockChain = res.blockNumber; 
              // *************** REGISTRO DE DIPLOMA EN LA BD *************** //
              if (res.blockNumber > 0){
                $.ajax({
                  method: "POST",
                  dataType: 'JSON',
                  url: '/controlador/c_diploma.php/?operacion=insertar',
                  data: { 
                    'id' : id,
                    'codigo_verificacion' : 'BC' + nroBloqueBlockChain.toString().padStart(9,'000000000') + $('#inscripcion_usuario_apellido_nombre' + id).html().slice(0, 2) + Math.floor(Math.random() * (99 - 10)),
                    'bloque_smart_contract' : nroBloqueBlockChain }
                }).done( async (resDip) => { 
                  diploma_id_generado = await resDip.id;
                }).then( ()=> {
                  $.ajax({
                      method: "POST",
                      dataType: 'JSON',
                      url: '/controlador/c_inscripcion.php/?operacion=actualizarIdDiploma',
                      data: { 
                        'id' : id,
                        'diploma_id' : diploma_id_generado }
                    }).done( async (resIns) => { 
                      mensajeDeRespuesta = await resIns.mensaje;
                      listarInscripcion('taller_id', taller_id_seleccionado);
                      await alert(mensajeDeRespuesta);
                    });
                });
              }
            });
            await $('#loading').attr("hidden", true); //Oculta la leyenda de loading
          }
        }

        function verDiploma(inscripcion_id){
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_diploma.php/?operacion=confeccionar&inscripcion_id=' + inscripcion_id
          }).done( async (res) => {
            await jQuery('<form target="_blank" action="' + res.ruta + '" method="get"></form>').appendTo('body').submit().remove();
          });
        }

        function confirmarMSJ(mensaje){
          return confirm('¿Está seguro que quiere ' + mensaje);
        }

        $('#btn_filtrar_tabla_modal').click( (e) => {
          $('#contenidoTablaModal').empty();
          let filtro = $("#filtro_tabla-modal").val(), valor = $("#valor_lista_modal").val();
          $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_taller.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => {
              for (let i = 0; i < res.length; i++) {
                  $('#contenidoTablaModal').append( 
                      '<tr id="' + res[i].id + '">' +
                          '<th><p class="text-sm-center fw-light lh-1" id="filtroLista_id' + res[i].id + '">' + res[i].id + '</p></th>' +
                          '<td><p class="text-sm-center fw-light lh-1" id="filtroLista_titulo' + res[i].id + '">' + res[i].titulo + '</p></td>' +
                          '<td><p class="text-sm-center fw-light lh-1" id="filtroLista_fecha_inicio' + res[i].id + '">' + res[i].fecha_inicio + '</p></td>' +
                          '<td><p class="text-sm-center fw-light lh-1" id="filtroLista_fecha_cierre' + res[i].id + '">' + res[i].fecha_cierre + '</p></td>' +
                          '<td class="btn-group">' +
                              '<button type="button" class="btn btn-sm btn-dark" id="filtroLista_boton' + res[i].id + '" data-bs-dismiss="modal" onclick="obtenerTaller(' + res[i].id + ');">Obtener</button>' +
                          '</td>' +
                      '</tr>');
              }
          });               
        });

    </script>