    <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
        <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray">Gestión De Copias De Seguridad</h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
        <form class="was-validated" accept-charset="utf-8" id="formulario">
            <div class="row g-3">

                <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                    <label for="copia_seguridad" class="form-label">Copia de seguridad</label>
                    <div class="input-group mb-3">
                    <input type="text" class="form-control form-control-sm" id="copia_seguridad" required>
                        <div class="input-group-prepend">
                            <button class="btn btn-sm btn-dark" type="button" onclick="clickearInputFile();">Cargar</button>
                            <button type="submit" class="btn btn-sm btn-danger" id="btnRestaurar">Restaurar</button>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 offset-md-4">
                    <input type="file" accept=".sql" id="copia_seguridad_file" hidden>
                </div>

                <!-- ============ BOTONES ============ -->
                <div class="col-md-4 offset-md-4">
                    <div class="d-grid gap-2"><button type="button" class="btn btn-sm btn-dark" id="btnRespaldar">Respaldar copia de seguridad</button></div>
                </div>

                <div class="col-md-4 offset-md-4">
                    <p class="text-center" id="leyenda"></p>
                </div>

            </div>
        </form>
    </main>

    <!-- =================== PANEL: IMAGEN LOADING =================== -->
    <div class="text-center my-3" id="loading" hidden>
      <img src="img/ajax-loader.gif"><br/>
      Restaurando base de datos.<br>
      El proceso puede tardar varios segundos…
    </div>

    <script type="text/javascript">
            
        var copia_seleccionada = '';

        function clickearInputFile(){
            $('#copia_seguridad_file').click();
        }
        
        $("#copia_seguridad_file").change( (e) => {
            copia_seleccionada = e.target.files[0].name;
            $("#copia_seguridad").val(copia_seleccionada);
        });

        $("#btnRestaurar").click( (e) => {
            if (confirmarMSJ('restaurar la base de datos?') === true){
                $('#loading').attr("hidden", false); //Muestra la leyenda de loading
                $("#formulario").validate({submitHandler: function(form) { 
                    $.ajax({
                        method: 'GET',
                        dataType: 'JSON',
                        url: '/controlador/c_copiaSeguridad.php/?operacion=restaurar&respaldo_nombre=' + copia_seleccionada,
                    }).done( async (resp) => { 
                        await $('#loading').attr("hidden", true); //Oculta la leyenda de loading
                        copia_seleccionada = await resp[0].nombre;
                        $("#copia_seguridad").val(resp[0].nombre);
                        $("#leyenda").html('');
                        await alert(resp[0].mensaje + (' copia de seguridad: ' + resp[0].nombre));
                    });      
                }});
            }
        });

        $("#btnRespaldar").click( (e) => {
            $.ajax({
                method: 'GET',
                dataType: 'JSON',
                url: '/controlador/c_copiaSeguridad.php/?operacion=respaldar',
            }).done( (resp) => { 
                copia_seleccionada = resp[0].nombre;
                $("#copia_seguridad").val('');
                $("#leyenda").html(resp[0].nombre);
                alert(resp[0].mensaje);
            });  
        });

        function confirmarMSJ(mensaje){
          return confirm('¿Está seguro que quiere ' + mensaje);
        }

    </script>