   <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
        <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray">Mis Suscripciones</h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
      <form class="was-validated" accept-charset="utf-8" id="formulario">
        <div class="row g-3">

              <!-- ============= TABLA ============= -->
              <div class="col-md-12 my-2">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="col">#</th>
                        <th class="col">Fecha Vto.</th>
                        <th class="col">Estado</th>
                        <th class="col">Importe</th>
                        <th class="col">Pago</th>
                        <th class="col"><div class="d-grid ps-md-2 pe-md-4"><button type="button" class="btn btn-sm btn-outline-primary" id="btn_agregar_suscripcion">Agregar</button></div></th>
                      </tr>
                    </thead>
                    <tbody id="contenidoTablaSuscripcion"></tbody>
                  </table>
                </div>
              </div>

        </div>
      </form>
    </main>

    <!-- =================== PANEL: IMAGEN LOADING =================== -->
    <div class="text-center my-3" id="loading" hidden>
      <img src="img/ajax-loader.gif"><br/>
      Accediendo a la plataforma de pago.<br>
      El proceso puede tardar algunos segundos…
    </div>

    <script type="text/javascript">

        var usuario_id_seleccionado;

        $("#btn_agregar_suscripcion").click( () => {
          if(usuario_id_seleccionado > 0){
            $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_suscripcion.php/?operacion=listar&filtro=usuario_id_deducir_nueva_suscripcion&valor=' + usuario_id_seleccionado,
            }).done( (res) => {
              if(typeof(res[0]) == "undefined") {
                if (confirmarMSJ('agregar una nueva suscripción') === true){
                  $.ajax({
                    method: "POST",
                    dataType: 'JSON',
                    url: '/controlador/c_suscripcion.php/?operacion=insertar',
                    data: { 
                      'id' : null,
                      'usuario_id' : usuario_id_seleccionado,
                      'fecha_vto' : null,
                      'importe' : 150.00,
                      'estado' : 'EN PROCESO' }
                  }).done( (res) => { 
                    mensajeDeRespuesta = res.mensaje;
                  }).then( ()=> {
                    listarSuscripcion('usuario_id', usuario_id_seleccionado)
                    alert(mensajeDeRespuesta);
                  });
                }
              }else{ alert('La suscripción está vigente o ya tiene una solicitud en proceso.'); }
            });
          }else{ alert('El usuario debe estar previamente cargado en el sistema para agregar una suscripción.'); }
        });

        function listarSuscripcion(filtro, valor) {
          $('#contenidoTablaSuscripcion').empty();
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_suscripcion.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => {
            for (let i = 0; i < res.length; i++) {
              $('#contenidoTablaSuscripcion').append( 
                '<tr id="' + res[i].id + '">' +
                '<th scope="row"><p class="text-sm-center pt-1" id="id' + res[i].id + '">' + res[i].id + '</th>' +
                  '<td><p class="text-sm-center pt-1" id="fecha_vto' + res[i].id + '">' + ((res[i].fecha_vto == null) ? "" : res[i].fecha_vto) + '</td>' +
                  '<td><p class="text-sm-center pt-1" id="importe' + res[i].id + '">$' + res[i].importe + '</td>' +
                  '<td><p class="text-sm-center pt-1" id="estado' + res[i].id + '">' + res[i].estado + '</td>' +
                  '<td><p class="text-sm-center pt-1" id="pago' + res[i].id + '">' + ((res[i].estado == "EN PROCESO") ? "PENDIENTE" : "PAGADO") + '</td>' +
                  '<td class="btn-group">' +
                    '<button type="button" class="btn btn-sm btn-dark" id="btnPagar' + res[i].id + '" onclick="pagarSuscripcion(' + res[i].id + ');" ' + ((res[i].estado != "EN PROCESO") ? "disabled hidden" : "") + '>Pagar</button>' +
                  '</td>' +
                '</tr>');
            }
          });               
        }

        function deducirNuevaSuscripcion(usuario_id) {
          let deduccionNuevaSuscripcion = 'no';
          $.ajax({
            method: 'GET',
            dataType: 'JSON',
            url: '/controlador/c_suscripcion.php/?operacion=listar&filtro=usuario_id_deducir_nueva_suscripcion&valor=' + usuario_id,
          }).done( (res) => {return false;
            if(typeof(res[0]) == "undefined") { return false;}
          });
          alert(de); 
        }

        async function pagarSuscripcion(suscripcion_id){
          if (confirmarMSJ('pagar la suscripción seleccionada?') === true){
            await $('#loading').attr("hidden", false); //Muestra la leyenda de loading
            await $.ajax({
              method: "POST",
              dataType: 'JSON',
              url: '/controlador/c_suscripcion.php/?operacion=pagar',
              data: { 
                'id' : suscripcion_id,
                'usuario_id' : usuario_id_seleccionado,
                'importe' : 150.00 }
            }).done( async (res) => {
              window.location = await res.url;
            });
            await $('#loading').attr("hidden", true); //Oculta la leyenda de loading
          }
        }

        function confirmarMSJ(mensaje){
          return confirm('¿Está seguro que quiere ' + mensaje);
        }

        //Acción: Auto-carga las suscripciones correspondientes al usuario que accedio al sistema 
        $.ajax({
          method: 'GET',
          dataType: 'JSON',
          url: '/controlador/c_usuario.php/?operacion=obtenerSesion'
        }).done( async (res) => {
          usuario_id_seleccionado = await res.id;
          await listarSuscripcion('usuario_id', usuario_id_seleccionado);
        });
        
    </script>