    <!-- ===================== PANEL: SUBTITULO ====================== -->
    <div class="row mb-3">
      <h3 class="text-center" style="text-shadow: 0.04em 0.04em 0.12em gray" id="tituloPrincipal">Registrarse En El Sistema</h3>
    </div>

    <!-- ===================== PANEL: FORMULARIO ===================== -->
    <main>
      <form class="was-validated" accept-charset="utf-8" id="formulario">
        <div class="row g-3">
  
          <div class="col-md-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control form-control-sm" name="nombre" id="nombre" maxlength="30" required>
          </div>
              
          <div class="col-md-3">
            <label for="apellido" class="form-label">Apellido</label>
            <input type="text" class="form-control form-control-sm" name="apellido" id="apellido" maxlength="30" required>
          </div>

          <div class="col-md-2">
            <label for="documento_tipo_id" class="form-label">Tipo de Documento</label>
              <select class="form-select form-select-sm" name="documento_tipo_id" id="documento_tipo_id" required>
                <option selected value="1">DNI</option>
                <option value="2">CC</option>
                <option value="3">CI</option>
              </select>
          </div>
          
          <div class="col-md-2">
            <label for="documento_nro" class="form-label">Nro. de Documento</label>
            <input type="number" class="form-control form-control-sm" name="documento_nro" id="documento_nro" minlength="7" maxlength="9" required>
          </div>

          <div class="col-md-2">
            <label for="sexo" class="form-label">Sexo</label>
            <select class="form-select form-select-sm" name="sexo" id="sexo" required>
              <option value="F">F</option>
              <option selected value="M">M</option>
            </select>
          </div>

          <div class="col-md-8">
            <div class="row g-3">
              <div class="col-md-5 col-lg-4">
                <label for="fecha_nacimiento" class="form-label">Fecha de Nacimiento</label>
                <input type="date" class="form-control form-control-sm" name="fecha_nacimiento" id="fecha_nacimiento" value="1980-06-01" required>
              </div>

              <div class="col-md-7 col-lg-8">
                <label for="correo_electronico" class="form-label">Correo Electrónico</label>
                <input type="email" class="form-control form-control-sm" name="correo_electronico" id="correo_electronico" maxlength="70" required>
              </div>
            
              <div class="col-md-9">
                <label for="direccion" class="form-label">Dirección</label>
                <input type="text" class="form-control form-control-sm" name="direccion" id="direccion" maxlength="50" required>
              </div>

              <div class="col-md-3">
                <label for="codigo_postal" class="form-label">Código Postal</label>
                <input type="number" class="form-control form-control-sm" name="codigo_postal" id="codigo_postal" maxlength="6" required>
              </div>

              <div class="col-md-4">
                <label for="localidad" class="form-label">Localidad</label>
                <input type="text" class="form-control form-control-sm" name="localidad" id="localidad" maxlength="20" required>
              </div>

              <div class="col-md-4">
                <label for="provincia" class="form-label">Provincia</label>
                <input type="text" class="form-control form-control-sm" name="provincia" id="provincia" maxlength="20" required>
              </div>

              <div class="col-md-4">
                <label for="pais_id" class="form-label">País</label>
                <select class="form-select form-select-sm" id="pais_id" required>
                  <option selected value="1">ARGENTINA</option>
                  <option value="2">BOLIVIA</option>
                  <option value="3">BRASIL</option>
                  <option value="4">CHILE</option>
                  <option value="5">COLOMBIA</option>
                  <option value="6">COSTA RICA</option>
                  <option value="7">CUBA</option>
                  <option value="8">ECUADOR</option>
                  <option value="9">EL SALVADOR</option>
                  <option value="10">GUATEMALA</option>
                  <option value="11">HAITÍ</option>
                  <option value="12">HONDURAS</option>
                  <option value="13">MÉXICO</option>
                  <option value="14">NICARAGUA</option>
                  <option value="15">PANAMÁ</option>
                  <option value="16">PARAGUAY</option>
                  <option value="17">PERÚ</option>
                  <option value="18">URUGUAY</option>
                  <option value="19">VENEZUELA</option>
                </select>
              </div>

              <div class="col-md-4">
                <label for="contrasenia" class="form-label">Contraseña</label>
                <input type="password" class="form-control form-control-sm" name="contrasenia" id="contrasenia" minlength="8" maxlength="12">
              </div>
                
              <!-- ============= TABLA ============= -->
              <div class="col-md-12 my-2">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="col">#</th>
                        <th class="col">Teléfono</th>
                        <th class="col">Prefijo</th>
                        <th class="col">Número</th>
                        <th class="col"><div class="d-grid ps-md-2 pe-md-4"><button type="button" class="btn btn-sm btn-outline-primary" id="btn_agregar_telefono">Agregar</button></div></th>
                      </tr>
                    </thead>
                    <tbody id="contenidoTablaTelefono"></tbody>
                  </table>
                </div>
              </div>

            </div>
          </div>

          <!-- ========== FOTOGRAFIA =========== -->
          <div class="col-md-4">
            <div class="col-md-12">
              <label for="fotografiaINPUT" class="form-label">Fotografía</label>
              <input class="form-control form-control-sm" type="file" accept=".jpg, .jpeg;capture=camera" id="fotografiaFILE" capture="environment">
              <img src="/public_html/img/img_default.jpg" class="img-fluid rounded-1 border border-1 mt-1" id="fotografiaSRC">
            </div>
          </div>

          <!-- ============ BOTONES ============ -->
          <div class="col-md-12">
            <div class="row mt-3">
              <div class="col-md-4 offset-md-4 col-lg-2 offset-lg-5 my-1"><div class="d-grid gap-2"><button type="submit" class="btn btn-sm btn-dark" id="btn_guardar_usuario">Guardar</button></div></div>
            </div>
          </div>
        </div>
      </form>
    </main>

    <script type="text/javascript">
        
      var mensajeDeRespuesta; 
      var operacion = "insertar";
      var usuario_id_seleccionado = 999999999999999;
      var direccion_id_seleccionada = 999999999999999;
      var contrasenia_id_seleccionada = 0;
      var contrasenia_hash_seleccionada = '';

      $("#btn_guardar_usuario").click( (e) => {
        $("#formulario").validate({submitHandler: function(form) { 
          let mensaje = (operacion === 'insertar') ? 'guardar el nuevo registro' : 'guardar los cambios realizados' ;
          if (confirmarMSJ(mensaje) === true){
            let formulario = new FormData();
            formulario.append('id', usuario_id_seleccionado);
            formulario.append('rol', 'SOCIO');
            formulario.append('nombre', $("#nombre").val());
            formulario.append('apellido', $("#apellido").val());
            formulario.append('documento_tipo_id', $("#documento_tipo_id").val());
            formulario.append('documento_nro', $("#documento_nro").val());
            formulario.append('sexo', $("#sexo").val());
            formulario.append('fecha_nacimiento', $("#fecha_nacimiento").val());
            formulario.append('correo_electronico', $("#correo_electronico").val());
            formulario.append('fotografiaSRC', $('#fotografiaSRC').attr('src'));
            formulario.append('fotografiaFILE', $('#fotografiaFILE')[0].files[0]);
            formulario.append('estado', 'ACTIVO');
            $.ajax({
                method: "POST",
                dataType: 'JSON',
                url: '/controlador/c_usuario.php/?operacion=' + operacion,
                data: formulario,
                contentType: false,
                processData: false
            }).done( (res) => { 
                mensajeDeRespuesta = res.mensaje;
                usuario_id_seleccionado = res.id;
                if (res.estado) {
                    guardarDireccion(); //Importante: Respetar el orden en el hilo de ejecución
                    guardarUltimaContrasenia(); //Importante: Respetar el orden en el hilo de ejecución
                }
              }).then( (res) => { 
                if ($('#tituloPrincipal').html() != 'Mi Usuario') { location.reload(); }; //Importante: 
                alert(mensajeDeRespuesta); //Importante: Respetar el orden en el hilo de ejecución
              });
          }
        }});
      });

      function obtenerUsuario(id){
          resetear('todo');
          $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_usuario.php/?operacion=obtener&id=' + id
          }).done( (res) => { 
              usuario_id_seleccionado = res.id;
              $("#nombre").val(res.nombre);
              $("#apellido").val(res.apellido);
              $("#documento_tipo_id").val(res.documento_tipo.id);
              $("#documento_nro").val(res.documento_nro);
              $("#sexo").val(res.sexo);
              $("#fecha_nacimiento").val(res.fecha_nacimiento);
              $("#correo_electronico").val(res.correo_electronico);
              $('#fotografiaSRC').attr('src', res.fotografia);
              listarDireccion('usuario_id',id);
              listarUltimaContrasenia('usuario_id_contrasenia_ultima', id);
              listarTelefono('usuario_id', id); 
          });
      }

      function guardarDireccion(){
          $.ajax({
              method: "POST",
              dataType: 'JSON',
              url: '/controlador/c_direccion.php/?operacion=' + operacion,
              data: { 
                  'id' : direccion_id_seleccionada,
                  'usuario_id' : usuario_id_seleccionado,
                  'direccion' : $("#direccion").val(),
                  'codigo_postal' : $("#codigo_postal").val(),
                  'localidad' : $("#localidad").val(),
                  'provincia' : $("#provincia").val(),
                  'pais_id' : $("#pais_id").val() }
          }).done( (res) => {
              direccion_id_seleccionada = res.id;
          });
      }

      function listarDireccion(filtro, valor) {
          resetear('direccion');
          $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_direccion.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => { 
              direccion_id_seleccionada = res[0].id;
              $("#direccion").val(res[0].direccion);
              $("#codigo_postal").val(res[0].codigo_postal);
              $("#localidad").val(res[0].localidad);
              $("#provincia").val(res[0].provincia);
              $("#pais_id").val(res[0].pais.id);
          });              
      }

      $("#btn_agregar_telefono").click( () => {
          if(usuario_id_seleccionado != 999999999999999){
              if (operacion == 'insertar' || operacion == 'actualizar') {
                  var id_tmp = Math.floor(Math.random() * 999999999999999);
                  $('#contenidoTablaTelefono').append( 
                      '<tr id="' + id_tmp + '">' +
                          '<th scope="row"><p class="text-sm-center pt-1" id="telefono_id' + id_tmp + '">N</th>' +
                          '<td>' + 
                              '<select class="form-select form-select-sm" id="telefono_tipo' + id_tmp + '" style="width: 160px;">' +
                                  '<option value="TELEFONO FIJO">TELEFONO FIJO</option>' +
                                  '<option selected value="TELEFONO MOVIL">TELEFONO MOVIL</option>' +                            '</select>' +
                          '</td>' +
                          '<td><input type="number" class="form-control form-control-sm" id="telefono_prefijo' + id_tmp + '" value="264" maxlength="5" required></td>' +
                          '<td><input type="number" class="form-control form-control-sm" id="telefono_numero' + id_tmp + '" value="" maxlength="9" required></td>' +
                          '<td class="btn-group">' +
                              '<button type="button" class="btn btn-sm btn-dark" id="btnGuardar' + id_tmp + '" onclick="guardarTelefono(\'insertar\', ' + id_tmp + ');">Guardar</button>' +
                              '<button type="button" class="btn btn-sm btn-danger" id="btnQuitar' + id_tmp + '" onclick="quitarTelefono(' + id_tmp + ');">Quitar</button>' +
                          '</td>' +
                      '</tr>');
              }
          }else{ alert('El usuario debe estar previamente cargado en el sistema para agregar sus teléfonos.'); }
      });
      
      function quitarTelefono(id){
          if (id > 99999999999999) {
              $('#' + id).remove();                   
          }else{
              if (confirmarMSJ('eliminar el registro?') === true){
                  $.ajax({
                      method: "POST",
                      dataType: 'JSON',
                      url: '/controlador/c_telefono.php/?operacion=eliminar',
                      data: { 'id' : $("#telefono_id" + id).text(), }
                  }).done( (res) => { 
                      $('#' + id).remove();                   
                      alert(res.estado);
                  });
              } 
          }
      }

      function guardarTelefono(operacion, id){
          let mensaje = (operacion === 'insertar') ? 'guardar el nuevo registro' : 'guardar los cambios realizados' ;
          if (confirmarMSJ(mensaje) === true){
              $.ajax({
                  method: "POST",
                  dataType: 'JSON',
                  url: '/controlador/c_telefono.php/?operacion=' + operacion,
                  data: { 
                      'id' : id,
                      'usuario_id' : usuario_id_seleccionado,
                      "telefono_tipo" : $("#telefono_tipo" + id).val(),
                      "telefono_prefijo" : $("#telefono_prefijo" + id).val(),
                      "telefono_numero" : $("#telefono_numero" + id).val() }
              }).done( (res) => { 
                  mensajeDeRespuesta = res.mensaje;
                  $('#' + id).attr("id", res.id);
                  $('#telefono_id' + id).attr("id", "telefono_id" + res.id).text(res.id);
                  $('#telefono_tipo' + id).attr("id", "telefono_tipo" + res.id);
                  $('#telefono_prefijo' + id).attr("id", "telefono_prefijo" + res.id);
                  $('#telefono_numero' + id).attr("id", "telefono_numero" + res.id);
                  $('#btnGuardar' + id).attr("id", "btnGuardar" + res.id).attr("onclick", "guardarTelefono('actualizar' ," + res.id + ");");
                  $('#btnQuitar' + id).attr("id", "btnQuitar" + res.id).attr("onclick", "quitarTelefono(" + res.id + ");");
              }).then( ()=> {
                  alert(mensajeDeRespuesta);
              });
          }
      }

      function listarTelefono(filtro, valor) {
          resetear('telefono');
          $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_telefono.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => {
              for (let i = 0; i < res.length; i++) {
                  $('#contenidoTablaTelefono').append( 
                      '<tr id="' + res[i].id + '">' +
                          '<th scope="row"><p class="text-sm-center pt-1" id="telefono_id' + res[i].id + '">' + res[i].id + '</p></th>' +
                          '<td>' + 
                              '<select class="form-select form-select-sm" id="telefono_tipo' + res[i].id + '" style="width: 160px;">' +
                                  '<option ' + ((res[i].tipo ==='TELEFONO FIJO') ? "selected":"") + ' value="TELEFONO FIJO">TELEFONO FIJO</option>' +
                                  '<option ' + ((res[i].tipo ==='TELEFONO MOVIL') ? "selected":"") + ' value="TELEFONO MOVIL">TELEFONO MOVIL</option>' +
                              '</select>' +
                          '</td>' +
                          '<td><input type="number" class="form-control form-control-sm" id="telefono_prefijo' + res[i].id + '" value="' + res[i].prefijo + '" maxlength="5" required></td>' +
                          '<td><input type="number" class="form-control form-control-sm" id="telefono_numero' + res[i].id + '" value="' + res[i].numero + '" maxlength="9" required></td>' +
                          '<td class="btn-group">' +
                              '<button type="button" class="btn btn-sm btn-dark" id="btnGuardar' + res[i].id + '" onclick="guardarTelefono(\'actualizar\', ' + res[i].id + ');">Guardar</button>' +
                              '<button type="button" class="btn btn-sm btn-danger" id="btnQuitar' + res[i].id + '" onclick="quitarTelefono(' + res[i].id +');">Quitar</button>' +
                          '</td>' +
                      '</tr>');
              }
          });               
      }

      function guardarUltimaContrasenia(){
          $.ajax({
              method: "POST",
              dataType: 'JSON',
              url: '/controlador/c_contrasenia.php/?operacion=' + operacion,
              data: { 
                  'id' : contrasenia_id_seleccionada,
                  'usuario_id' : usuario_id_seleccionado,
                  'contrasenia' : $("#contrasenia").val(),
                  'hash_original' : contrasenia_hash_seleccionada }
          }).done( (res) => {
              if (res.id > 0){
                contrasenia_id_seleccionada = res.id; 
              }else{
                alert(res.mensaje); //Importante: Respetar el orden en el hilo de ejecución
              }
         });
      }

      function listarUltimaContrasenia(filtro, valor) {
          resetear('contrasenia');
          $.ajax({
              method: 'GET',
              dataType: 'JSON',
              url: '/controlador/c_contrasenia.php/?operacion=listar&filtro=' + filtro + '&valor=' + valor,
          }).done( (res) => { 
              contrasenia_id_seleccionada = res[0].id;
              contrasenia_hash_seleccionada = res[0].hash;
          });              
      }

      function resetear(seccion){
          if(seccion == 'usuario' || seccion == 'todo'){
              operacion = 'insertar';
              usuario_id_seleccionado = 999999999999999;
              $("#nombre").val('');
              $("#apellido").val('');
              $("#documento_tipo").val('1');
              $("#documento_nro").val('');
              $("#sexo").val('MASCULINO');
              $("#fecha_nacimiento").val('1980-06-01');
              $('#fotografiaSRC').attr('src', 'img/img_default.jpg'); 
              $('#fotografiaFILE').val(null); //Importante: Libera el "input file"
              $("#correo_electronico").val('');
          }
          if(seccion == 'direccion' || seccion == 'todo'){
              direccion_id_seleccionada = 999999999999999;
              $("#direccion").val('');
              $("#codigo_postal").val('');
              $("#localidad").val('');
              $("#provincia").val('');
              $("#pais").val('1');
          }
          if(seccion == 'contrasenia' || seccion == 'todo'){
            contrasenia_id_seleccionada = 0;
            contrasenia_hash_seleccionada = '';
            $('#contrasenia').val('');
          }
          if(seccion == 'telefono' || seccion == 'todo'){
              $('#contenidoTablaTelefono').empty();
          } 
      }

      function confirmarMSJ(mensaje){
          return confirm('¿Está seguro que quiere ' + mensaje);
      }
      
      $('#fotografiaFILE').change( (e) => {
          let lector = new FileReader();
          if(e.target.files[0] != null){
              lector.readAsDataURL(e.target.files[0]); //Lee el archivo subido 
              lector.onloadend = () => { 
                  var fotografia = new Image(100, 200);
                  fotografia.src = lector.result;
                  fotografia.onload = function() { $('#fotografiaSRC').attr('src', fotografia.src); }; //Muestra la fotografia cuando ha terminado su lectura 
              }
          }
          else $('#fotografiaSRC').attr('src', '');
      });

      //Acción: Auto-carga las suscripciones correspondientes al usuario que accedio al sistema 
      $.ajax({
        method: 'GET',
        dataType: 'JSON',
        url: '/controlador/c_usuario.php/?operacion=obtenerSesion'
      }).done( async (res) => {
        operacion = "actualizar";
        usuario_id_seleccionado = await res.id;
        $('#tituloPrincipal').html('Mi Usuario');
        await obtenerUsuario(usuario_id_seleccionado);
      });

  </script>